[package]
name = "eventually-rs-installation-issue"
version = "0.1.0"
edition = "2024"

[dependencies]
eventually = "0.4.0"
eventually-postgres = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.2"
